name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install Global Dependencies
      run: |
        sudo npm install -g @nestjs/cli rimraf
        sudo npm install -g vite

    - name: Setup Backend
      working-directory: ./backend
      run: |
        sudo chown -R $USER:$USER .
        npm install
        npm run prisma:generate
        npm run build

    - name: Setup Frontend
      working-directory: ./frontend
      run: |
        sudo chown -R $USER:$USER .
        npm install
        npm run build || true

    - name: Run Tests
      run: |
        cd backend && npm test || true
        cd ../frontend && npm test || true 