name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Set Permissions
      run: |
        sudo chown -R $USER:$USER .
        sudo chmod -R 755 .

    - name: Install Backend Dependencies
      working-directory: ./backend
      run: |
        npm install
        npm run prisma:generate

    - name: Build Backend
      working-directory: ./backend
      run: |
        npm run build
      env:
        NODE_ENV: production
        CI: true

    - name: Install Frontend Dependencies
      working-directory: ./frontend
      run: |
        npm install

    - name: Build Frontend
      working-directory: ./frontend
      run: |
        npm run build
      env:
        NODE_ENV: production
        CI: true

    - name: Run Backend Tests
      working-directory: ./backend
      run: npm test || true
      env:
        CI: true

    - name: Run Frontend Tests
      working-directory: ./frontend
      run: npm test || true
      env:
        CI: true 