name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install and Build Backend
      working-directory: ./backend
      run: |
        echo "Installing backend dependencies..."
        npm ci
        echo "Generating Prisma client..."
        npx prisma generate
        echo "Building backend..."
        npm run build

    - name: Install and Build Frontend
      working-directory: ./frontend
      run: |
        echo "Installing frontend dependencies..."
        npm ci
        echo "Building frontend..."
        npm run build 