name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install Global Dependencies
      run: |
        sudo npm install -g @nestjs/cli
        sudo npm install -g vite

    - name: Install Backend Dependencies
      working-directory: ./backend
      run: |
        npm install

    - name: Install Frontend Dependencies
      working-directory: ./frontend
      run: |
        npm install

    - name: Build Backend
      working-directory: ./backend
      run: |
        npm run build

    - name: Build Frontend
      working-directory: ./frontend
      run: |
        npm run build || true

    - name: Run Backend Tests
      working-directory: ./backend
      run: |
        npm test || true

    - name: Run Frontend Tests
      working-directory: ./frontend
      run: |
        npm test || true 