name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Clean Backend
      working-directory: ./backend
      run: rm -rf dist node_modules

    - name: Install Backend Dependencies
      working-directory: ./backend
      run: |
        echo "Installing backend dependencies..."
        npm install
        echo "Generating Prisma client..."
        npx prisma generate

    - name: Build Backend
      working-directory: ./backend
      run: |
        echo "Building backend..."
        npx nest build

    - name: Clean Frontend
      working-directory: ./frontend
      run: rm -rf dist node_modules

    - name: Install Frontend Dependencies
      working-directory: ./frontend
      run: |
        echo "Installing frontend dependencies..."
        npm install

    - name: Build Frontend
      working-directory: ./frontend
      run: |
        echo "Building frontend..."
        npm run build 