name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install Global Dependencies
      run: |
        npm install -g @nestjs/cli
        npm install -g vite

    - name: Install Dependencies
      run: |
        npm install --workspaces

    - name: Build Projects
      run: |
        npm run build --workspaces || true

    - name: Run Tests
      run: |
        npm run test --workspaces || true 