name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    # Backend
    - name: Install Backend Dependencies
      working-directory: ./backend
      run: |
        echo "Installing backend dependencies..."
        npm install
        npm install -g @nestjs/cli

    - name: Build Backend
      working-directory: ./backend
      run: |
        echo "Building backend..."
        npm run build

    # Frontend
    - name: Install Frontend Dependencies
      working-directory: ./frontend
      run: |
        echo "Installing frontend dependencies..."
        npm install
        npm install -g vite

    - name: Build Frontend
      working-directory: ./frontend
      run: |
        echo "Building frontend..."
        npm run build || true

    # Tests
    - name: Run Backend Tests
      working-directory: ./backend
      run: |
        echo "Running backend tests..."
        npm test || true

    - name: Run Frontend Tests
      working-directory: ./frontend
      run: |
        echo "Running frontend tests..."
        npm test || true 