name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'

    - name: Cache Backend Dependencies
      uses: actions/cache@v3
      with:
        path: |
          backend/node_modules
        key: ${{ runner.os }}-backend-${{ hashFiles('backend/package-lock.json') }}

    - name: Cache Frontend Dependencies
      uses: actions/cache@v3
      with:
        path: |
          frontend/node_modules
        key: ${{ runner.os }}-frontend-${{ hashFiles('frontend/package-lock.json') }}

    - name: Install Global Dependencies
      run: |
        sudo npm install -g @nestjs/cli
        sudo npm install -g vite

    - name: Install Backend Dependencies
      working-directory: ./backend
      run: |
        sudo chown -R $USER:$(id -gn $USER) .
        npm ci || npm install

    - name: Build Backend
      working-directory: ./backend
      run: |
        npm run prisma:generate
        NODE_ENV=production npm run build

    - name: Install Frontend Dependencies
      working-directory: ./frontend
      run: |
        sudo chown -R $USER:$(id -gn $USER) .
        npm ci || npm install

    - name: Build Frontend
      working-directory: ./frontend
      run: |
        NODE_ENV=production npm run build

    - name: Run Tests
      run: |
        cd backend && npm test || true
        cd ../frontend && npm test || true 