name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install Global Dependencies
      run: |
        sudo npm install -g rimraf
        sudo npm install -g @nestjs/cli
        which rimraf

    - name: Backend - Clean
      working-directory: ./backend
      run: |
        echo "Cleaning backend..."
        rimraf dist node_modules package-lock.json

    - name: Backend - Install
      working-directory: ./backend
      run: |
        echo "Installing backend dependencies..."
        npm install

    - name: Backend - Build
      working-directory: ./backend
      run: |
        echo "Building backend..."
        npm run build
        echo "Generating Prisma client..."
        npx prisma generate

    - name: Frontend - Clean
      working-directory: ./frontend
      run: |
        echo "Cleaning frontend..."
        rimraf dist node_modules package-lock.json

    - name: Frontend - Install
      working-directory: ./frontend
      run: |
        echo "Installing frontend dependencies..."
        npm install

    - name: Frontend - Build
      working-directory: ./frontend
      run: |
        echo "Building frontend..."
        npm run build