name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install Global Dependencies
      run: |
        sudo npm install -g @nestjs/cli
        sudo npm install -g rimraf

    - name: Install and Build Backend
      working-directory: ./backend
      run: |
        rm -rf node_modules dist
        npm install
        npm run prisma:generate
        npm run build
      env:
        NODE_ENV: production
        CI: true

    - name: Install and Build Frontend
      working-directory: ./frontend
      run: |
        rm -rf node_modules dist
        npm install
        npm run build
      env:
        NODE_ENV: production
        CI: true

    - name: Run Backend Tests
      working-directory: ./backend
      run: npm test || true
      env:
        CI: true

    - name: Run Frontend Tests
      working-directory: ./frontend
      run: npm test || true
      env:
        CI: true 