name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install Backend Dependencies
      working-directory: ./backend
      run: |
        npm install
        npx prisma generate

    - name: Build Backend
      working-directory: ./backend
      env:
        NODE_ENV: production
      run: npm run build

    - name: Install Frontend Dependencies
      working-directory: ./frontend
      run: npm install

    - name: Build Frontend
      working-directory: ./frontend
      env:
        NODE_ENV: production
      run: npm run build

    - name: Run Backend Tests
      working-directory: ./backend
      run: npm test || true

    - name: Run Frontend Tests
      working-directory: ./frontend
      run: npm test || true 