name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install NestJS CLI
      run: npm install -g @nestjs/cli

    - name: Backend - Install Dependencies
      working-directory: ./backend
      run: |
        echo "Installing backend dependencies..."
        rm -rf node_modules package-lock.json dist
        npm install --no-workspaces

    - name: Backend - Generate Prisma
      working-directory: ./backend
      run: |
        echo "Generating Prisma client..."
        npx prisma generate

    - name: Backend - Build
      working-directory: ./backend
      run: |
        echo "Building backend..."
        npx nest build

    - name: Frontend - Install Dependencies
      working-directory: ./frontend
      run: |
        echo "Installing frontend dependencies..."
        rm -rf node_modules package-lock.json dist
        npm install --no-workspaces

    - name: Frontend - Build
      working-directory: ./frontend
      run: |
        echo "Building frontend..."
        npm run build 