name: Deploy to Heroku

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      - name: Install dependencies
        working-directory: ./backend
        run: |
          npm install
          npm install -g @nestjs/cli
          sudo npm install -g prisma

      - name: Generate Prisma Client
        working-directory: ./backend
        run: |
          sudo npx prisma generate

      - name: Build application
        working-directory: ./backend
        run: |
          npm run build

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: attendance-argjend
        run: |
          cd backend
          git init
          git add .
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git commit -m "Deploy to Heroku"
          git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git || true
          heroku buildpacks:clear --app $HEROKU_APP_NAME || true
          heroku buildpacks:set heroku/nodejs --app $HEROKU_APP_NAME
          git push heroku HEAD:main --force 