name: Deploy

on:
  push:
    branches:
      - main      # deploy to production
      - develop   # deploy to staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Deploy Backend
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        APP_NAME: ${{ github.ref == 'refs/heads/main' && 'prod-backend-arjan' || 'staging-backend' }}
      run: |
        heroku container:login
        cd backend
        heroku container:push web -a $APP_NAME
        heroku container:release web -a $APP_NAME
        
    - name: Deploy Frontend
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        APP_NAME: ${{ github.ref == 'refs/heads/main' && 'prod-frontend-arjan' || 'staging-frontend-arjan' }}
      run: |
        heroku container:login
        cd frontend
        heroku container:push web -a $APP_NAME
        heroku container:release web -a $APP_NAME 