name: Deploy to Heroku

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      - name: Build and prepare for deployment
        run: |
          # Build frontend
          cd frontend
          npm install
          npm install -D @rollup/rollup-linux-x64-gnu
          npm install -D vite @vitejs/plugin-react
          npm run build
          cd ..

          # Build backend
          cd backend
          npm install
          npm install -g @nestjs/cli
          npm run build
          cd ..

          # Create deployment directory with clean structure
          mkdir -p deploy
          cd deploy
          
          # Copy only the necessary backend files
          cp -r ../backend/package*.json .
          cp -r ../backend/dist .
          cp -r ../backend/prisma .
          mkdir -p public
          cp -r ../frontend/dist/* public/

          # Install production dependencies
          npm install --production
          
          # Create Procfile
          echo "web: npm start" > Procfile

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: attendance-argjend
        run: |
          cd deploy
          git init
          git add .
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git commit -m "Deploy to Heroku"
          git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git || true
          heroku buildpacks:clear --app $HEROKU_APP_NAME || true
          heroku buildpacks:set heroku/nodejs --app $HEROKU_APP_NAME
          heroku config:set NPM_CONFIG_PRODUCTION=false --app $HEROKU_APP_NAME
          heroku config:set NODE_ENV=production --app $HEROKU_APP_NAME
          
          # Add Prisma and other necessary environment variables
          heroku config:set DATABASE_URL=${{ secrets.DATABASE_URL }} --app $HEROKU_APP_NAME
          heroku config:set JWT_SECRET=${{ secrets.JWT_SECRET }} --app $HEROKU_APP_NAME
          
          # Add post-build commands for Prisma
          echo "
          {
            \"scripts\": {
              \"postinstall\": \"prisma generate && npm run build\",
              \"build\": \"nest build\",
              \"start\": \"node dist/main.js\"
            }
          }" > package.json.tmp
          jq -s '.[0] * .[1]' package.json package.json.tmp > package.json.new
          mv package.json.new package.json
          rm package.json.tmp

          git add .
          git commit -m "Update package.json with Prisma setup"
          
          git push heroku HEAD:main --force 