name: Deploy to Heroku

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      - name: Build and prepare for deployment
        run: |
          # Build frontend
          cd frontend
          npm install
          npm install -D @rollup/rollup-linux-x64-gnu
          npm install -D vite @vitejs/plugin-react
          npm run build
          cd ..

          # Build backend first
          cd backend
          npm ci
          npm install -g @nestjs/cli
          npm run build
          cd ..

          # Create deployment directory
          mkdir -p deploy
          
          # Copy backend files
          cp -r backend/* deploy/
          cp -r backend/dist deploy/
          rm -rf deploy/public || true
          mkdir -p deploy/public
          cp -r frontend/dist/* deploy/public/
          
          # Create production package.json
          cd deploy
          jq '. + {
            "scripts": {
              "start": "node dist/main.js",
              "build": "nest build"
            },
            "engines": {
              "node": "18.x"
            },
            "dependencies": {
              "@nestjs/cli": "^10.0.0",
              "@nestjs/common": "^10.0.0",
              "@nestjs/core": "^10.0.0",
              "@nestjs/jwt": "^10.0.0",
              "@nestjs/passport": "^10.0.0",
              "@nestjs/platform-express": "^10.0.0",
              "@nestjs/swagger": "^7.0.0",
              "@prisma/client": "^5.0.0",
              "class-validator": "^0.14.0",
              "dayjs": "^1.11.10",
              "passport": "^0.6.0",
              "passport-jwt": "^4.0.1",
              "prisma": "^5.0.0",
              "reflect-metadata": "^0.1.13",
              "rxjs": "^7.8.1",
              "@types/passport-jwt": "^3.0.8"
            }
          }' package.json > package.json.new
          mv package.json.new package.json

          # Create Procfile
          echo "web: npm start" > Procfile

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: attendance-argjend
        run: |
          cd deploy
          git init
          git add .
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git commit -m "Deploy to Heroku"
          git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git || true
          heroku buildpacks:clear --app $HEROKU_APP_NAME || true
          heroku buildpacks:set heroku/nodejs --app $HEROKU_APP_NAME
          heroku config:set NPM_CONFIG_PRODUCTION=false --app $HEROKU_APP_NAME
          heroku config:set NODE_ENV=production --app $HEROKU_APP_NAME
          git push heroku HEAD:main --force 