name: Deploy to Heroku

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Install dependencies and build
        run: |
          # Install frontend dependencies and build
          cd frontend
          npm install
          npm run build
          cd ..

          # Install backend dependencies and build
          cd backend
          npm install
          npm run build
          cd ..

          # Copy frontend build to backend dist
          mkdir -p backend/dist
          cp -r frontend/dist/* backend/dist/

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: attendance-argjend
          heroku_email: argjend.k@excelentis.org
          procfile: "web: cd backend && npm install --omit=dev && npm start"
